using HrmAiOps.Domain.Core;

// Request and response DTO records - extracted from top-level Program.cs
public sealed record CreateCustomerRequest(string Code, string Name, string? Industry, string? Timezone);
public sealed record CreateProjectRequest(string Code, string Name, string? Description, string? HrmProductName);
public sealed record UpsertEnvironmentRequest(string Name, EnvironmentKind Kind, string? BaseUrl, bool RequiresApproval);
public sealed record RepositoryRequest(Guid? EnvironmentId, string Provider, string RepoUrl, string DefaultBranch, string SecretRef);
public sealed record DatabaseProfileRequest(Guid EnvironmentId, string Engine, string Host, int Port, string DatabaseName, string? UsernameRef, string SecretRef, bool ReadOnly);
public sealed record RequirementRequest(string Title, string ContentText, string? CreatedBy);
public sealed record RequirementUploadRequest(string Title, string SourceFileRef, string ExtractedText, string? CreatedBy);
public sealed record ConfigSpecGenerateRequest(Guid? EnvironmentId, string? ModuleName);
public sealed record RequirementUpdateRequest(string Title, string ContentText, WorkStatus Status, string? UpdatedBy);
public sealed record DocumentUpdateRequest(string Title, string Content, WorkStatus Status, string? UpdatedBy);
public sealed record ConfigSpecUpdateRequest(string ModuleName, string Content, WorkStatus Status, RiskLevel? RiskLevel, string? UpdatedBy);
public sealed record SignOffRequest(string SignedOffBy, string? Role, string? Comment);
public sealed record ReviewAiProposalRequest(string ReviewedBy, string? Comment, string? EditedContent);
public sealed record PromptTemplateRequest(string Key, string Name, AiTaskType TaskType, string Description, string SystemPrompt, string UserPromptTemplate, string OutputJsonSchema, string? CreatedBy);
public sealed record PromptTemplateVersionRequest(string SystemPrompt, string UserPromptTemplate, string OutputJsonSchema, string? CreatedBy);
public sealed record IssueRequest(Guid? EnvironmentId, string? LinkedEntityType, Guid? LinkedEntityId, string Title, string Description, IssueCategory? Category, IssueSeverity Severity, IssuePriority Priority, string? ReportedBy);
public sealed record CloseIssueRequest(string ClosedBy, string? ResolutionNote);
public sealed record ChangeRequestRequest(Guid? IssueId, Guid? FixProposalId, string Title, string Description, Guid TargetEnvironmentId);
public sealed record SubmitApprovalRequest(string? RequestedBy, string? ApproverUserId);
public sealed record ApprovalActionRequest(string? Comment);
public sealed record ReleaseRequest(Guid? ChangeRequestId, Guid TargetEnvironmentId, string Version, string? ReleaseNotes, string? DeploymentPlan);
public sealed record DeployReleaseRequest(string? SourceCommit, string? ArtifactRef, string? DatabaseBackupRef, string? ConfigSnapshotRef);
public sealed record KnowledgeArticleRequest(Guid? ProjectId, Guid? IssueId, string Title, string Category, string Content);
public sealed record ConnectorRequest(Guid? ProjectId, Guid? EnvironmentId, Guid? PermissionPolicyId, string ConnectorType, string Name, string? BaseUrl, string SecretRef, string ConfigJson);
public sealed record ConnectorPolicyRequest(Guid? EnvironmentId, string Name, bool AllowSchemaRead, bool AllowConfigRead, bool AllowLogRead, bool AllowSourceMetadataRead, bool AllowHealthCheck, bool AllowTestApply, bool AllowProductionApplyWithApproval, string? MaskingProfile);
public sealed record TestApplyRequest(Guid EnvironmentId, Guid? ConnectorId, string SourceType, Guid SourceId, string? RequestedBy);
public sealed record ExecuteApplyRequest(string? RequestedBy);
public sealed record CreateProductionReleasePackageRequest(Guid ReleaseReadinessReportId, Guid? ProductionEnvironmentId, string Version, string? Title);
public sealed record CompleteChecklistItemRequest(string? EvidenceRef);
public sealed record ReleaseWindowRequest(DateTimeOffset StartsAt, DateTimeOffset EndsAt, string? Timezone);
public sealed record ManualConfirmationRequest(string? ConfirmedBy);
public sealed record ValidationCheckRequest(PostReleaseValidationStatus Status, string? Evidence);
public sealed record RollbackDecisionRequestDto(string Reason, string Impact);
public sealed record GenerateLearningRequest(bool AllowLowRiskAutoApprove, string? RequestedBy);
public sealed record ReviewKnowledgeRequest(string ReviewedBy, string? Comment);
public sealed record SupersedeKnowledgeRequest(string Title, string Content, string LessonsLearned, string ReviewedBy);
public sealed record RecalculateGovernanceRequest(string? ModuleName, string? RequestedBy);
public sealed record TenantAccessRequest(Guid? ProjectId, string UserId, string RoleKey, DateTimeOffset? ExpiresAt);
public sealed record SecurityRoleRequest(string RoleKey, string Name, string Description, string[] PermissionKeys);
public sealed record SecretVaultReferenceRequest(Guid? ProjectId, string Name, string SecretRef, string VaultProvider, DateTimeOffset? RotationDueAt);
public sealed record SecretAccessRequest(Guid? ProjectId, string SecretRef, string Purpose);
public sealed record DataClassificationRuleRequest(Guid? ProjectId, string ResourceType, string FieldName, DataClassificationLevel Classification, string MaskingStrategy, bool ApplyToAiPrompt);
public sealed record MaskPreviewRequest(Guid? ProjectId, string ResourceType, string Text);
public sealed record AiAccessPolicyRequest(AiTaskType TaskType, string AllowedRolesCsv, DataClassificationLevel MaxInputClassification, bool MaskingRequired, bool RequiresApprovalForHighRisk);
public sealed record ConnectorSecurityPolicyRequest(Guid? EnvironmentId, string ConnectorType, string AllowedActionsCsv, string RequiredPermission, DataClassificationLevel MaxDataClassification, bool ReadOnlyRequired, bool AllowTestApply, bool AllowProductionApplyWithApproval);
public sealed record ApprovalGovernanceRuleRequest(string RuleKey, string ModuleName, RiskLevel? MinimumRiskLevel, bool AppliesToProduction, int RequiredApprovalSteps, string ApproverRolesCsv, bool RequiresSecurityApproval, string Reason);
public sealed record GenerateComplianceEvidenceRequest(Guid? AuditLogId, Guid? ApprovalRequestId, string ControlId, string Title, string Summary, string EntityType, Guid? EntityId, string? EvidenceRef);
public sealed record ServicePlanRequest(string PlanCode, string Name, string Description, decimal BaseMonthlyPrice, string Currency, int MaxProjects, int MaxConnectors, int MaxAiRunsPerMonth, int MaxTicketsPerMonth, int IncludedSupportHours, int SlaResponseHours, int SlaResolutionHours, string EnabledModulesCsv, QuotaEnforcementMode QuotaEnforcementMode);
public sealed record CustomerContractRequest(string Title, ContractStatus Status, DateTimeOffset StartsAt, DateTimeOffset EndsAt, string Currency, decimal ContractValue, string TermsSummary, string BillingContactRef);
public sealed record SubscriptionRequest(Guid ServicePlanId, Guid? ContractId, SubscriptionStatus Status, BillingCycle BillingCycle, DateTimeOffset StartsAt, DateTimeOffset? EndsAt, DateTimeOffset CurrentPeriodStart, DateTimeOffset CurrentPeriodEnd, decimal? UnitPrice);
public sealed record PortalTicketRequest(string Title, string Description, IssueSeverity Severity, string? RequestedBy);
public sealed record TicketActionRequest(DateTimeOffset? At, string? Note);
public sealed record ServiceRequestDto(Guid? PortalTicketId, string RequestType, string Title, string Description, RiskLevel RiskLevel, decimal EstimatedHours, string? RequestedBy);
public sealed record GenerateBillingDraftRequest(Guid SubscriptionId, DateTimeOffset PeriodStart, DateTimeOffset PeriodEnd);
public sealed record InvoiceDraftRequest(DateTimeOffset IssueDate, DateTimeOffset DueDate);
public sealed record PaymentTrackingRequest(string PaymentRef, PaymentTrackingStatus Status, decimal Amount, DateTimeOffset? RecordedAt, string Notes);
public sealed record GenerateServiceReportRequest(Guid? SubscriptionId, DateTimeOffset PeriodStart, DateTimeOffset PeriodEnd);
public sealed record GenerateReportExportRequest(Guid? TemplateId, ReportDocumentType ReportType, ReportOutputFormat OutputFormat, ReportVisibility Visibility, DateTimeOffset DateFrom, DateTimeOffset DateTo, bool ExternalExport);
public sealed record GenerateDashboardSummaryRequest(DateTimeOffset? DateFrom, DateTimeOffset? DateTo);
public sealed record IntegrationProviderRequest(Guid? ProjectId, string ProviderKey, string Name, IntegrationProviderCategory Category, string BaseUrl, string DocumentationUrl, bool SupportsInboundWebhook, bool SupportsOutboundWebhook, bool SupportsSignatureVerification, bool SupportsRetry, int DefaultTimeoutSeconds, string ConfigJson);
public sealed record IntegrationEndpointRequest(Guid? ProjectId, Guid ProviderId, string EndpointKey, string Name, IntegrationDirection Direction, string HttpMethod, string PathOrUrl, IntegrationAuthType AuthType, string? SecretRef, int TimeoutSeconds, DataClassificationLevel MaxDataClassification, bool MaskOutboundPayloads);
public sealed record IntegrationPayloadMappingRequest(Guid? ProjectId, Guid ProviderId, Guid? EndpointId, string MappingKey, string SourceSystem, string TargetSystem, IntegrationEventType EventType, string MappingJson);
public sealed record IntegrationEventSubscriptionRequest(Guid? ProjectId, Guid ProviderId, Guid? EndpointId, IntegrationEventType EventType, string SubscriptionKey, string FilterJson);
public sealed record WebhookOutboundSubscriptionRequest(Guid? ProjectId, Guid ProviderId, Guid? EndpointId, IntegrationEventType EventType, string TargetUrl, string? SecretRef, WebhookSignatureMode SignatureMode, int MaxRetryAttempts, int RetryBackoffSeconds, int TimeoutSeconds);
public sealed record ApiGatewayRouteRequest(Guid? ProjectId, string RouteKey, string PublicPath, string InternalTarget, string HttpMethod, string AllowedExternalSystem, string RequiredPermission, string TokenSecretRef, int TimeoutSeconds, DataClassificationLevel MaxDataClassification, string AccessPolicyJson);
public sealed record IntegrationOutboundTestRequest(Guid? ProjectId, IntegrationEventType EventType, string PayloadJson, string? CorrelationId);
public sealed record InboundWebhookDto(Guid? ProjectId, Guid? EndpointId, IntegrationEventType EventType, string PayloadJson, string? CorrelationId);
public sealed record GatewayInvocationDto(Guid? ProjectId, string ExternalSystem, string PayloadJson, string? CorrelationId);
public sealed record IntegrationAutomationTriggerRequest(Guid? ProjectId, Guid? ProviderId, string TriggerKey, IntegrationEventType EventType, IntegrationAutomationActionType ActionType, string ConditionJson, string ActionJson, bool CreateOnFailureOnly);
public sealed record DevOpsRepositoryRequest(DevOpsProviderKind Provider, string Name, string ProviderRepositoryId, string RepoUrl, string DefaultBranch, string SecretRef);
public sealed record DevOpsBranchCreateDto(string BranchName, string SourceBranch, bool CreatedByAi);
public sealed record DevOpsPullRequestRequest(string SourceBranch, string TargetBranch, string Title, string Description, RiskLevel RiskLevel, string ChangeAreasCsv, bool CreatedByAi);
public sealed record AiCodeAnalysisDto(string BranchName, string DiffText);
public sealed record AiPatchProposalDto(string BranchName, string Intent);
public sealed record DevOpsReviewDto(string ReviewerUserId, CodeReviewDecision Decision, string Comments);
public sealed record DevOpsApprovalDto(string ApproverUserId);
public sealed record DevOpsPipelineRequest(Guid RepositoryId, string PipelineKey, string Name, DevOpsProviderKind Provider, string ConfigPath, int TimeoutSeconds);
public sealed record DevOpsPipelineRunDto(Guid RepositoryId, Guid? PullRequestId, PipelineRunType RunType, string InputJson);
public sealed record DevOpsPackageDto(string Version);
public sealed record DevOpsMergeDto(bool RequestedByAi);
public sealed record AiCodeGovernancePolicyDto(Guid? RepositoryId, string PolicyKey, string ProtectedBranchesCsv, bool RequireHumanReview, bool BlockDirectMainMerge, bool BlockAiProductionDeploy, bool HighRiskRequiresApproval, string SpecialApprovalAreasCsv, int MaxDiffBytes, bool Active);
public sealed record TelemetrySourceRequest(Guid? ProjectId, Guid? EnvironmentId, Guid? ConnectorId, Guid? ProductionReleasePackageId, Guid? ProductionDeploymentRunId, string SourceKey, string Name, TelemetrySourceType SourceType, string EndpointRef, int PollIntervalSeconds, int TimeoutSeconds, bool MaskLogs);
public sealed record TelemetryIngestDto(Guid? ProjectId, Guid TelemetrySourceId, Guid? EnvironmentId, Guid? ConnectorId, Guid? ProductionReleasePackageId, Guid? ProductionDeploymentRunId, TelemetrySignalType SignalType, TelemetryHealthStatus HealthStatus, string MetricName, decimal? MetricValue, string Unit, int? ApiLatencyMs, decimal? UptimePercent, string Summary, string PayloadJson, string? CorrelationId);
public sealed record MonitoringRuleRequest(Guid? ProjectId, Guid? TelemetrySourceId, string RuleKey, string Name, TelemetrySignalType SignalType, string MetricName, MonitoringRuleOperator Operator, decimal? ThresholdValue, string MatchText, AlertSeverity Severity, bool AutoCreateIncident, bool AutoCreateIssue, bool Active);
public sealed record AlertRuleRequest(Guid? ProjectId, Guid? MonitoringRuleId, string AlertKey, AlertSeverity MinimumSeverity, NotificationChannel Channel, string RecipientRef, bool CreateNotification, bool CreateEscalationForCritical, bool Active);
public sealed record IncidentRequest(Guid? ProjectId, Guid? EnvironmentId, Guid? ConnectorId, Guid? ProductionReleasePackageId, Guid? ProductionDeploymentRunId, Guid? IssueId, Guid? SlaPolicyId, Guid? AlertEventId, string Title, string Description, AlertSeverity Severity, IncidentPriority Priority, string ImpactSummary);
public sealed record IncidentResolveDto(string Resolution);
public sealed record DataImportTemplateDto(string TemplateKey, string Name, HrmDataDomain Domain, ImportFileType DefaultFileType, DataClassificationLevel MaxClassification, string SchemaJson, string SampleFileRef);
public sealed record DataImportFileDto(Guid? EnvironmentId, Guid? TemplateId, string FileRef, string FileName, ImportFileType FileType, long SizeBytes, int RowCount, DataClassificationLevel Classification, string PreviewJson);
public sealed record DataColumnMappingDto(Guid TemplateId, int TemplateVersion, string MappingKey, string SourceColumn, string TargetEntity, string TargetField, string TransformExpression, DataClassificationLevel DataClassification);
public sealed record DataValidationRuleDto(Guid? TemplateId, string RuleKey, string Name, HrmDataDomain Domain, string TargetField, ValidationRuleType RuleType, string ExpressionJson, ValidationIssueSeverity Severity);
public sealed record DataImportBatchDto(Guid EnvironmentId, Guid? ConnectorId, Guid TemplateId, int TemplateVersion, Guid ImportFileId, HrmDataDomain Domain);
public sealed record DataImportApplyDto(bool Confirmed);
public sealed record DataAiAssistanceDto(Guid? BatchId, Guid? TemplateId, AiDataAssistanceType AssistanceType, string Context);
public sealed record DataSignOffDto(string SignedBy, string Role, string Comment);
public sealed record PortalUserRequest(string UserId, string DisplayName, string Email, string RoleKey, bool CanViewBilling, bool CanViewReports, bool CanApprove);
public sealed record PortalRequestDto(string RequestType, string Title, string Description, string Priority);
public sealed record PortalRequirementIntakeRequest(Guid? PortalRequestId, string Title, string BusinessContext, string RequirementText);
public sealed record PortalDocumentShareRequest(string DocumentType, Guid DocumentId, int DocumentVersion, PortalVisibility Visibility, DateTimeOffset? ExpiresAt);
public sealed record PortalDocumentReviewRequest(PortalApprovalStatus Status, string? Comment);
public sealed record PortalApprovalDecisionRequest(string? Comment);
public sealed record PortalAiChatSessionRequest(string Title);
public sealed record PortalAiChatMessageRequest(string Message);
public sealed record PortalCommentRequest(Guid ProjectId, string SourceEntityType, Guid SourceEntityId, string Message, PortalVisibility Visibility);
public sealed record PortalAttachmentRequest(Guid ProjectId, string SourceEntityType, Guid SourceEntityId, string FileName, string ContentType, string StorageRef, PortalVisibility Visibility);
public sealed record NotificationTemplateRequest(Guid? ProjectId, string TemplateKey, string Name, NotificationType NotificationType, NotificationChannel Channel, NotificationRecipientType RecipientType, string SubjectTemplate, string BodyTemplate, DataClassificationLevel MaxClassification);
public sealed record NotificationTemplateVersionRequestDto(string SubjectTemplate, string BodyTemplate, DataClassificationLevel MaxClassification);
public sealed record WorkflowRuleRequest(Guid? ProjectId, string RuleKey, string Name, WorkflowTriggerType TriggerEvent, string ConditionJson, string ActionJson, int Priority);
public sealed record WorkflowEventRequest(Guid? ProjectId, WorkflowTriggerType TriggerEvent, string SourceEntityType, Guid? SourceEntityId, string Message);
public sealed record CollaborationTaskRequest(string Title, string Description, string AssigneeUserId, NotificationRecipientType AssigneeType, CollaborationTaskPriority Priority, DateTimeOffset? DueAt, string SourceEntityType, Guid? SourceEntityId);
public sealed record EscalationRequest(string SourceEntityType, Guid SourceEntityId, string Reason, string EscalatedToUserId);
