using HrmAiOps.Domain.Core;

namespace HrmAiOps.Application.Abstractions;

public interface IAppStore
{
    SynchronizedList<Customer> Customers { get; }
    SynchronizedList<Project> Projects { get; }
    SynchronizedList<ProjectEnvironment> Environments { get; }
    SynchronizedList<SourceRepository> SourceRepositories { get; }
    SynchronizedList<DatabaseProfile> DatabaseProfiles { get; }
    SynchronizedList<Requirement> Requirements { get; }
    SynchronizedList<UrsDocument> UrsDocuments { get; }
    SynchronizedList<Blueprint> Blueprints { get; }
    SynchronizedList<ConfigSpec> ConfigSpecs { get; }
    SynchronizedList<DocumentSignOff> DocumentSignOffs { get; }
    SynchronizedList<HrmModuleDefinition> HrmModules { get; }
    SynchronizedList<Issue> Issues { get; }
    SynchronizedList<IssueAnalysis> IssueAnalyses { get; }
    SynchronizedList<FixProposal> FixProposals { get; }
    SynchronizedList<ChangeRequest> ChangeRequests { get; }
    SynchronizedList<ApprovalRequest> ApprovalRequests { get; }
    SynchronizedList<ApprovalStep> ApprovalSteps { get; }
    SynchronizedList<Release> Releases { get; }
    SynchronizedList<RegressionTestPlan> RegressionTestPlans { get; }
    SynchronizedList<ReleaseDraft> ReleaseDrafts { get; }
    SynchronizedList<RollbackPoint> RollbackPoints { get; }
    SynchronizedList<KnowledgeArticle> KnowledgeArticles { get; }
    SynchronizedList<AiRun> AiRuns { get; }
    SynchronizedList<AiPromptTemplate> AiPromptTemplates { get; }
    SynchronizedList<AiPromptTemplateVersion> AiPromptTemplateVersions { get; }
    SynchronizedList<AiProposal> AiProposals { get; }
    SynchronizedList<CustomerConnector> CustomerConnectors { get; }
    SynchronizedList<ConnectorPermissionPolicy> ConnectorPermissionPolicies { get; }
    SynchronizedList<ConnectorRun> ConnectorRuns { get; }
    SynchronizedList<EnvironmentSnapshot> EnvironmentSnapshots { get; }
    SynchronizedList<SnapshotDiff> SnapshotDiffs { get; }
    SynchronizedList<ApplyRun> ApplyRuns { get; }
    SynchronizedList<ApplyStep> ApplySteps { get; }
    SynchronizedList<ApplyLog> ApplyLogs { get; }
    SynchronizedList<RollbackPlan> RollbackPlans { get; }
    SynchronizedList<RegressionTestRun> RegressionTestRuns { get; }
    SynchronizedList<ReleaseReadinessReport> ReleaseReadinessReports { get; }
    SynchronizedList<ProductionReleasePackage> ProductionReleasePackages { get; }
    SynchronizedList<ReleaseChecklistItem> ReleaseChecklistItems { get; }
    SynchronizedList<ReleaseWindow> ReleaseWindows { get; }
    SynchronizedList<ProductionDeploymentPlan> ProductionDeploymentPlans { get; }
    SynchronizedList<ProductionDeploymentStep> ProductionDeploymentSteps { get; }
    SynchronizedList<ProductionDeploymentRun> ProductionDeploymentRuns { get; }
    SynchronizedList<DeploymentStepRun> DeploymentStepRuns { get; }
    SynchronizedList<ProductionDeploymentLog> ProductionDeploymentLogs { get; }
    SynchronizedList<PostReleaseValidationCheck> PostReleaseValidationChecks { get; }
    SynchronizedList<RollbackDecisionRequest> RollbackDecisionRequests { get; }
    SynchronizedList<ReleaseCommunication> ReleaseCommunications { get; }
    SynchronizedList<PostReleaseTask> PostReleaseTasks { get; }
    SynchronizedList<ReleaseClosureReport> ReleaseClosureReports { get; }
    SynchronizedList<KnowledgeLearningItem> KnowledgeLearningItems { get; }
    SynchronizedList<RepeatedIssuePattern> RepeatedIssuePatterns { get; }
    SynchronizedList<GovernanceScoreSnapshot> GovernanceScoreSnapshots { get; }
    SynchronizedList<GovernanceInsight> GovernanceInsights { get; }
    SynchronizedList<AiPerformanceMetric> AiPerformanceMetrics { get; }
    SynchronizedList<TenantAccessGrant> TenantAccessGrants { get; }
    SynchronizedList<SecurityRole> SecurityRoles { get; }
    SynchronizedList<SecurityPermission> SecurityPermissions { get; }
    SynchronizedList<SecurityRolePermission> SecurityRolePermissions { get; }
    SynchronizedList<UserRoleAssignment> UserRoleAssignments { get; }
    SynchronizedList<SecurityPolicyRule> SecurityPolicyRules { get; }
    SynchronizedList<SecretVaultReference> SecretVaultReferences { get; }
    SynchronizedList<SecretAccessAudit> SecretAccessAudits { get; }
    SynchronizedList<DataClassificationRule> DataClassificationRules { get; }
    SynchronizedList<AiAccessPolicy> AiAccessPolicies { get; }
    SynchronizedList<ConnectorSecurityPolicy> ConnectorSecurityPolicies { get; }
    SynchronizedList<ApprovalGovernanceRule> ApprovalGovernanceRules { get; }
    SynchronizedList<ComplianceEvidence> ComplianceEvidence { get; }
    SynchronizedList<ServicePlan> ServicePlans { get; }
    SynchronizedList<CustomerContract> CustomerContracts { get; }
    SynchronizedList<Subscription> Subscriptions { get; }
    SynchronizedList<SupportEntitlement> SupportEntitlements { get; }
    SynchronizedList<SlaPolicy> SlaPolicies { get; }
    SynchronizedList<CustomerPortalTicket> CustomerPortalTickets { get; }
    SynchronizedList<ServiceRequest> ServiceRequests { get; }
    SynchronizedList<UsageRecord> UsageRecords { get; }
    SynchronizedList<UsageQuotaSnapshot> UsageQuotaSnapshots { get; }
    SynchronizedList<BillingDraft> BillingDrafts { get; }
    SynchronizedList<BillingLineItem> BillingLineItems { get; }
    SynchronizedList<InvoiceDraft> InvoiceDrafts { get; }
    SynchronizedList<PaymentTrackingRecord> PaymentTrackingRecords { get; }
    SynchronizedList<CustomerServiceReport> CustomerServiceReports { get; }
    SynchronizedList<PortalUser> PortalUsers { get; }
    SynchronizedList<PortalProjectAccess> PortalProjectAccesses { get; }
    SynchronizedList<PortalRequest> PortalRequests { get; }
    SynchronizedList<PortalRequirementIntake> PortalRequirementIntakes { get; }
    SynchronizedList<PortalDocumentShare> PortalDocumentShares { get; }
    SynchronizedList<PortalDocumentReview> PortalDocumentReviews { get; }
    SynchronizedList<PortalApproval> PortalApprovals { get; }
    SynchronizedList<PortalKnowledgeArticle> PortalKnowledgeArticles { get; }
    SynchronizedList<PortalTrainingSection> PortalTrainingSections { get; }
    SynchronizedList<PortalAiChatSession> PortalAiChatSessions { get; }
    SynchronizedList<PortalAiChatMessage> PortalAiChatMessages { get; }
    SynchronizedList<PortalNotification> PortalNotifications { get; }
    SynchronizedList<PortalComment> PortalComments { get; }
    SynchronizedList<PortalAttachment> PortalAttachments { get; }
    SynchronizedList<PortalServiceReportShare> PortalServiceReportShares { get; }
    SynchronizedList<PortalBillingSummaryView> PortalBillingSummaryViews { get; }
    SynchronizedList<NotificationTemplate> NotificationTemplates { get; }
    SynchronizedList<NotificationTemplateVersion> NotificationTemplateVersions { get; }
    SynchronizedList<NotificationDeliveryLog> NotificationDeliveryLogs { get; }
    SynchronizedList<WorkflowRule> WorkflowRules { get; }
    SynchronizedList<WorkflowRun> WorkflowRuns { get; }
    SynchronizedList<WorkflowActionLog> WorkflowActionLogs { get; }
    SynchronizedList<CollaborationTask> CollaborationTasks { get; }
    SynchronizedList<ReminderSchedule> ReminderSchedules { get; }
    SynchronizedList<EscalationEvent> EscalationEvents { get; }
    SynchronizedList<ActivityTimelineEntry> ActivityTimelineEntries { get; }
    SynchronizedList<ReportTemplate> ReportTemplates { get; }
    SynchronizedList<ReportTemplateVersion> ReportTemplateVersions { get; }
    SynchronizedList<ReportGenerationJob> ReportGenerationJobs { get; }
    SynchronizedList<ReportExportFile> ReportExportFiles { get; }
    SynchronizedList<PortalReportShare> PortalReportShares { get; }
    SynchronizedList<DashboardSnapshot> DashboardSnapshots { get; }
    SynchronizedList<IntegrationProvider> IntegrationProviders { get; }
    SynchronizedList<IntegrationEndpoint> IntegrationEndpoints { get; }
    SynchronizedList<IntegrationPayloadMapping> IntegrationPayloadMappings { get; }
    SynchronizedList<IntegrationEventSubscription> IntegrationEventSubscriptions { get; }
    SynchronizedList<WebhookOutboundSubscription> WebhookOutboundSubscriptions { get; }
    SynchronizedList<ApiGatewayRoute> ApiGatewayRoutes { get; }
    SynchronizedList<IntegrationAutomationTrigger> IntegrationAutomationTriggers { get; }
    SynchronizedList<IntegrationRun> IntegrationRuns { get; }
    SynchronizedList<IntegrationRunLog> IntegrationRunLogs { get; }
    SynchronizedList<DevOpsRepository> DevOpsRepositories { get; }
    SynchronizedList<DevOpsBranch> DevOpsBranches { get; }
    SynchronizedList<DevOpsPullRequest> DevOpsPullRequests { get; }
    SynchronizedList<CodeReviewRecord> CodeReviewRecords { get; }
    SynchronizedList<AiCodeAnalysis> AiCodeAnalyses { get; }
    SynchronizedList<AiPatchProposal> AiPatchProposals { get; }
    SynchronizedList<CiCdPipeline> CiCdPipelines { get; }
    SynchronizedList<PipelineRun> PipelineRuns { get; }
    SynchronizedList<DeploymentPackage> DeploymentPackages { get; }
    SynchronizedList<SourceCodeSnapshot> SourceCodeSnapshots { get; }
    SynchronizedList<DevOpsRun> DevOpsRuns { get; }
    SynchronizedList<DevOpsRunLog> DevOpsRunLogs { get; }
    SynchronizedList<AiCodeGovernancePolicy> AiCodeGovernancePolicies { get; }
    SynchronizedList<TelemetrySource> TelemetrySources { get; }
    SynchronizedList<RuntimeTelemetrySample> RuntimeTelemetrySamples { get; }
    SynchronizedList<TelemetryLogSummary> TelemetryLogSummaries { get; }
    SynchronizedList<MonitoringRule> MonitoringRules { get; }
    SynchronizedList<AlertRule> AlertRules { get; }
    SynchronizedList<AlertEvent> AlertEvents { get; }
    SynchronizedList<IncidentRecord> IncidentRecords { get; }
    SynchronizedList<IncidentAction> IncidentActions { get; }
    SynchronizedList<IncidentSlaBinding> IncidentSlaBindings { get; }
    SynchronizedList<AiIncidentDiagnosis> AiIncidentDiagnoses { get; }
    SynchronizedList<PostIncidentReview> PostIncidentReviews { get; }
    SynchronizedList<DataImportTemplate> DataImportTemplates { get; }
    SynchronizedList<DataImportTemplateVersion> DataImportTemplateVersions { get; }
    SynchronizedList<DataImportFile> DataImportFiles { get; }
    SynchronizedList<DataColumnMapping> DataColumnMappings { get; }
    SynchronizedList<DataValidationRule> DataValidationRules { get; }
    SynchronizedList<DataImportBatch> DataImportBatches { get; }
    SynchronizedList<DataImportRun> DataImportRuns { get; }
    SynchronizedList<DataValidationIssue> DataValidationIssues { get; }
    SynchronizedList<DataReconciliationReport> DataReconciliationReports { get; }
    SynchronizedList<DataMigrationReport> DataMigrationReports { get; }
    SynchronizedList<DataSignOff> DataSignOffs { get; }
    SynchronizedList<AiDataMigrationAssistance> AiDataMigrationAssistances { get; }
    SynchronizedList<TrainingPlan> TrainingPlans { get; }
    SynchronizedList<LearningPath> LearningPaths { get; }
    SynchronizedList<TrainingMaterial> TrainingMaterials { get; }
    SynchronizedList<TrainingLesson> TrainingLessons { get; }
    SynchronizedList<TrainingQuiz> TrainingQuizzes { get; }
    SynchronizedList<AssessmentResult> AssessmentResults { get; }
    SynchronizedList<TrainingSession> TrainingSessions { get; }
    SynchronizedList<TrainingAttendance> TrainingAttendances { get; }
    SynchronizedList<UserLearningProgress> UserLearningProgresses { get; }
    SynchronizedList<UserCertification> UserCertifications { get; }
    SynchronizedList<AdoptionMetric> AdoptionMetrics { get; }
    SynchronizedList<TrainingGap> TrainingGaps { get; }
    SynchronizedList<AiTrainingAssistantExchange> AiTrainingAssistantExchanges { get; }
    SynchronizedList<TraceLink> TraceLinks { get; }
    SynchronizedList<AuditLog> AuditLogs { get; }

    string NextNumber(string prefix);
}

